#cloud-config
write_files:
  - path: /etc/netplan/99-dns.yaml
    permissions: '0644'
    content: |
      network:
        ethernets:
          eth0:
            nameservers:
              search: [backend-00.iaas-ingress.contoso.com]
              addresses: [168.63.129.16]
runcmd:
  - [ netplan, apply ]
